# Generated by Django 4.1.4 on 2023-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('order_no', models.IntegerField()),
                ('total_cost', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(default='paid', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=5)),
            ],
        ),
    ]
