# Generated by Django 4.1.4 on 2023-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotellist',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=60)),
                ('star', models.IntegerField(default=0)),
                ('image', models.FileField(default=None,
                 max_length=2500, null=True, upload_to='image_folder/')),
                ('current_cost', models.FloatField()),
                ('delete_cost', models.FloatField()),
            ],
        ),
    ]
