# Generated by Django 4.1.4 on 2023-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinghotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.CharField(max_length=13)),
                ('no_people', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('userpassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
