# Generated by Django 4.1.4 on 2023-01-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookinghotel_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='start',
            field=models.DateField(default=None),
        ),
    ]
