# Generated by Django 4.1.4 on 2023-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookinghotel_city_bookinghotel_current_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
    ]
